# toolchain file copied from the carla UE4 build system and modified to meet lanelet lib building

# Automatically generated by Setup.sh

if(DEFINED ENV{UE4_ROOT})
  message(STATUS "Using tool chain under: $ENV{UE4_ROOT}")
else()
  message(FATAL_ERROR "Please define UE4_ROOT environment variable pointing to the carla's UE4 location")
endif()

set(UE4_COMPILER_LOCATION $ENV{UE4_ROOT}/Engine/Extras/ThirdPartyNotUE/SDKs/HostLinux/Linux_x64/v17_clang-10.0.1-centos7/x86_64-unknown-linux-gnu)
set(UE4_LIBCXX_LOCATION $ENV{UE4_ROOT}/Engine/Source/ThirdParty/Linux/LibCxx)

set(CMAKE_C_COMPILER ${UE4_COMPILER_LOCATION}/bin/clang)
set(CMAKE_CXX_COMPILER ${UE4_COMPILER_LOCATION}/bin/clang++)

# disable -Werror since the boost 1.72 doesn't compile with ad_rss without warnings (i.e. the geometry headers)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++14 -pthread -fPIC" CACHE STRING "" FORCE)
#set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -Wextra -Wpedantic" CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wdeprecated -Wshadow -Wuninitialized -Wunreachable-code" CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wpessimizing-move -Wold-style-cast -Wnull-dereference" CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wduplicate-enum -Wnon-virtual-dtor -Wheader-hygiene" CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wconversion -Wfloat-overflow-conversion" CACHE STRING "" FORCE)


# @todo These flags need to be compatible with setup.py compilation.
#set(CMAKE_CXX_FLAGS_RELEASE_CLIENT "${CMAKE_CXX_FLAGS_RELEASE} -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -std=c++14 -Wno-missing-braces -DBOOST_ERROR_CODE_HEADER_ONLY" CACHE STRING "" FORCE)

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -stdlib=libc++" CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -isystem ${UE4_LIBCXX_LOCATION}/include/c++/v1 --sysroot=${UE4_COMPILER_LOCATION} " CACHE STRING "" FORCE)
#set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fno-exceptions" CACHE STRING "" FORCE)

#NOTE, NO CMAKE_<LANG>_LINK_FLAGS can be found in CMAKE help, while CMAKE_<LANG>_FLAGS do exist.
add_link_options("LINKER:-L${UE4_LIBCXX_LOCATION}/lib/Linux/x86_64-unknown-linux-gnu")
add_link_options("LINKER:-lc++")
add_link_options("LINKER:-lc++abi")


#for debug
#set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -v" CACHE STRING "" FORCE)
#set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} --no-warnings" CACHE STRING "" FORCE)
